blog/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('', include('news.url')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class News(models.Model):
    category=models.ForeignKey(Category, on_delete=models.PROTECT)
    title=models.CharField(max_length=100, unique=True)
    slug=models.SlugField(max_length=100, unique=True)
    description=models.TextField(max_length=500)
    created_at=models.DateTimeField( auto_now_add=True)
    is_published=models.BooleanField(default=True)
    photo=models.ImageField(upload_to='photos/%Y/%M/%D')
    views=models.IntegerField(default=0)
    summary=models.TextField(max_length=250)

    def __str__(self):
        return self.title

class pages(models.Model):
    name=models.CharField(max_length=100)
    slug=models.SlugField(max_length=100)
    description=models.CharField(max_length=500)

    def __str__(self):
        return self.name

news/views.py
from django.shortcuts import render, redirect
from .models import *
from django.core.mail import send_mail
from django.contrib import messages
from django.http import HttpResponse

# Create your views here.

def index(request):
    data={
        'catData': Category.objects.all()
    }
    return render(request, 'pages/index.html', data)


def details(request, slug):
    newsData= News.objects.get(slug=slug)
    category= newsData.category.id
    related_news= News.objects.filter(category=category).exclude(id=newsData.id)
    data={
        'newsData': News.objects.get(slug=slug),
        'related_news': related_news,
    }
    return render(request,'pages/details.html', data)


def contact(request):
    if request.method == 'POST':
        name=request.POST['name']
        email=request.POST['email']
        comment=request.POST['comment']
        send_mail("from: " + email, comment, name,["grgtenzin0@gmail.com"],fail_silently=False,)
        messages.success(request, "your message was sent")
        back = request.META.get('HTTP_REFERER')
        return redirect(back)
    else:
        return render(request, 'pages/contact.html')

def category_news(request,slug):
    Category_data= Category.objects.get(slug=slug)
    data={
        'categoryData': Category_data,
    }
    return render(request, 'pages/category.html', data)

def news(request):
    if request.method=='POST':
        search =request.POST['search']
        find_data= News.objects.filter(title__icontains=search)| News.objects.filter(category__name__icontains=search)
        data={
        'newsD': find_data,
        }
        return render(request, 'pages/news.html', data)

def about(request,slug):
    data={
        'pageData': pages.objects.get(slug =slug)
    }
    return render(request, 'pages/about.html', data)

def money(request):
    return render(request, 'pages/money.html')

news/templates/pages/about.html
{% extends 'pages/main.html' %}

{% block content %}

<div class="row">
    <div class="col">
        <h1>{{pageData.name}}</h1>
        <hr>
        <br>
        <p>{{pageData.description}}</p>
    </div>
</div>

{% endblock %}

news/templates/pages/category.html
{% extends 'pages/main.html' %}

{% block content  %}

<div class="container">
    <div class="row">
        <h1>{{categoryData.name}}</h1>
    </div>
    <div class="row">
        {% for x in categoryData.news_set.all %}
        <div id="content">
            <!-- begin post -->
            <div class="post">
                <h2>{{x.name}}</h2>
                <div class="col">
                {% if x.photo %}
                <div class="thumb"><a href="#"><img src="{{x.photo.url}}" alt="image not found"/></a></div>
              {% endif %}
              <h3><a href="#">{{x.title}}</a></h3>
              <p class="date">Posted on {{x.created_at}}</p>
              <p>{{x.summary}}</p>
              <a class="continue" href="{% url 'details' x.slug %}">Continue Reading</a>
            </div>
            </div>
            <!-- end post -->
          </div>
        {% endfor %}
    </div>
</div>
<div class="relatednews">
    <!-- begin popular posts -->
    <h2>Related News</h2>
    <ul>
      <li><a href="{% url 'money' %}">Make Money Online quick with a simple trick</a></li>
    </ul>
    <!-- end popular posts -->
</div>

{% endblock  %}

news/templates/pages/contact.html
{% extends 'pages/main.html' %}

{% block content %}

<div id="content">
    <!-- begin post -->
    <div class="single">
      <h2>Contact Us</h2>
      <p>We would love to hear your feedback!</p>
    </div>
    <div class="row">
      {% if messages %}
      {% for x in messages %}
      <div class="alert" role="alert">
        {{x}}
      </div>
      {% endfor %}
      {% endif %}
    </div>
    <!-- end post -->
    <!-- begin comments -->
    <div id="comments">
      <div id="respond">
        <form action="{% url 'contact' %}" method="post" id="commentform" name="contact">
          {% csrf_token %}
          <p>
            <input type="text" name="name"  required id="name" value="" size="22" tabindex="1" />
            <label for="name"><small>Name (required)</small></label>
          </p><br>
          <p>
            <input type="text" name="email"  required id="email" value="" size="22" tabindex="2" />
            <label for="email"><small>Mail (will not be published) (required)</small></label>
          </p><br>
          <p>
            <textarea name="comment" type="text" required id="comment" cols="100%" rows="10" tabindex="4" placeholder="your feed back"></textarea>
          </p><br>
          <p>
            <button name="submit" type="submit" id="submit">Submit Comment</button>
          </p>
        </form>
      </div>
    </div>
    <!-- end comments -->
  </div>



{% endblock  %}

news/templates/pages/details.html
{% extends 'pages/main.html' %}

{% block content  %}
<br>
<br>

<div class="container">
    <div class="row">
        <img src="{{newsData.photo.url}}"  width="600px" height="300px" alt="image not found">
        <h1>{{newsData.title}}</h1>
        <p>{{newsData.description}}</p>
    </div>
</div>
<div class="relatednews">
    <!-- begin popular posts -->
    <h2>Related News</h2>
    <ul>
        {% for x in related_news %}
      <li><a href="{% url 'details' x.slug %}">{{x.title}}</a></li>
      {% endfor %}
    </ul>
    <!-- end popular posts -->
</div>
<div class="row">
    <div id="fb-root"></div>
    <div class="fb-comments" data-href="http://127.0.0.1:8000/details" data-width="" data-numposts="5"></div>
</div>

<br>
<hr>
<br>

{% endblock  %}

news/templates/pages/footer.html
<!-- BEGIN footer -->
<div id="footer">
    <p> &copy; - <a href="#">Django news</a> &middot; All Rights Reserved</p>
    <p>Sponser: <a href="http://www.wpthemedesigner.com/">lorem</a>
  </div>
  <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v16.0" nonce="3laVU7Px"></script>
  <!-- END footer -->

news/templates/pages/header.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
{% load static %}
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>
  {% if title %}
  {{title}} :: Django News
    {% else %}
  The Django News ::
{% endif %}
</title>
<link rel="icon" href="{% static 'photos/applogo.png' %}">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<link rel="stylesheet" type="text/css" href="{% static 'style1.css' %}"/>
<!--[if lte IE 6]><link rel="stylesheet" type="text/css" href="ie.css" /><![endif]-->
</head>
<body>
<!-- BEGIN wrapper -->
<div id="wrapper">
  <!-- BEGIN header -->
  <div id="header">
    <p class="links">More:
    {% for x in pageData.all %}
    <a href="{% url 'about' x.slug %}">{{x.name}} |</a>
    {% endfor %}
  </p>
    <div class="break"></div>
    <div class="logo">
      <h1><a href="#">DJANGO News</a></h1>
    </div>
    <div class="break"></div>
    <ol>
      <li><a href="/">Home</a></li>
      <li><a href="{% url 'contact' %}">Contact us</a></li>
      <div class="dropdown">
        <button class="dropbtn">Category<i class="fa fa-caret-down"></i></button>
        <div class="dropcontent">
          {% for x in globalData %}
          <a href="{% url 'category_news' x.slug %}">{{x.name}}</a>
          {% endfor %}
        </div>
      </div>
      <li>
     <!-- begin search -->
    <form class="search" action="{% url 'news' %}" method="post">
      {% csrf_token %}
      <input type="text" name="search" required id="search"/>
      <button type="submit">Search</button>
    </form>
    <!-- end search -->
      </li>
    </ol>
    <div class="break"></div>
  </div>
  <!-- END header -->

news/templates/pages/index.html
{% extends 'pages/main.html' %}

{% block content %}
  <!-- BEGIN content -->
  {% for x in catData %}
  {% if x.news_set.all.count > 0 %}
  <div id="content">
    <!-- begin post -->
    <div class="post">
        <h2>{{x.name}}</h2>
        <div class="col">
        {% for news in x.news_set.all %}
        {% if news.photo %}<br>
        <div class="thumb"><a href="#"><img src="{{news.photo.url}}" alt="image not found"/></a></div>
      {% endif %}
      <h3><a href="#">{{news.title}}</a></h3>
      <p class="date">Posted on {{news.created_at}}</p>
      <p>{{news.summary}}</p>
      <a class="continue" href="{% url 'details' news.slug %}">Continue Reading</a>
      {% endfor %}
    </div>
    </div>
    <!-- end post -->
  </div>
  {% endif %}
  {% endfor %}
  <hr>
  <!-- END content -->
  <!-- BEGIN sidebar -->
  <div id="sidebar">
    <div class="wrapper">
      <!-- begin popular posts -->
      <!-- BEGIN left -->
      <div class="l sbar">
      </div>
      <!-- END left -->
      <!-- BEGIN right -->

      <!-- END right -->
    </div>
  </div>
  <!-- END sidebar -->
<!-- END wrapper -->
</body>
</html>

{% endblock %}

news/templates/pages/main.html
{% include 'pages/header.html' %}

{% block content  %}

{% endblock  %}

{% include 'pages/footer.html' %}

news/templates/pages/money.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <blockquote>
        <h1>
            Makeking money fast is a myth
        </h1>
        <br>
        <a href="{% url 'index' %}"> Go to Home</a>
    </blockquote>
</body>
</html>

news/templates/pages/news.html
{% extends 'pages/main.html' %}

{% block content  %}
<h1> News List</h1>
<div class="container">
    <div class="row">
        <h1>{{newsD.name}}</h1>
    </div>
    <div class="row">
        {% for x in newsD %}
        <div id="content">
            <!-- begin post -->
            <div class="post">
                <h2>{{x.name}}</h2>
                <div class="col">
                {% if x.photo %}
                <div class="thumb"><a href="#"><img src="{{x.photo.url}}" alt="image not found"/></a></div>
              {% endif %}
              <h3><a href="#">{{x.title}}</a></h3>
              <p class="date">Posted on {{x.created_at}}</p>
              <p>{{x.summary}}</p>
              <a class="continue" href="{% url 'details' x.slug %}">Continue Reading</a>
            </div>
            </div>
            <!-- end post -->
          </div>
        {% endfor %}
    </div>
</div>
<div class="relatednews">
    <!-- begin popular posts -->
    <h2>Related News</h2>
    <ul>
      <li><a href="#">Make Money Online Creating Websites</a></li>
    </ul>
    <!-- end popular posts -->
</div>


{% endblock  %}